In [1]:
# Import the numpy package under the name "np"
import numpy as np

In [2]:
# Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.14.3
lapack_opt_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
openblas_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [3]:
# Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# How to find the memory size of any array
arr = np.arange(10)
arr.size * arr.itemsize # Number of elements * byte size of element

80

In [5]:
# How to get the documentation of the numpy add function from the command line
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

In [6]:
# Create a null vector of size 10 but the fifth value which is 1
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# Create a vector with values ranging from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# Reverse a vector (first element becomes last)
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

In [11]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create a 3x3x3 array with random values
np.random.rand(3,3,3)

array([[[0.1365404 , 0.31685765, 0.33100601],
        [0.13278508, 0.13881306, 0.24072328],
        [0.62017558, 0.25668276, 0.4512432 ]],

       [[0.06918851, 0.08532038, 0.00860696],
        [0.01592888, 0.16522495, 0.26569382],
        [0.71299871, 0.68604656, 0.27876494]],

       [[0.23101696, 0.79821652, 0.79910528],
        [0.24045492, 0.14083185, 0.81558821],
        [0.19746956, 0.35500169, 0.44416183]]])

In [13]:
# Create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.rand(10,10)
print(arr)
print("Min: {}".format(np.min(arr)))
print("Max: {}".format(np.max(arr)))

[[6.63747691e-01 9.58177667e-02 9.70415688e-01 9.92737895e-01
  7.66173767e-02 8.13789331e-01 6.63435622e-01 1.07345817e-01
  6.19896025e-01 1.74053167e-01]
 [4.59313878e-01 5.61960893e-01 3.33651354e-01 2.77120791e-01
  9.57467850e-01 5.31858883e-01 8.16113743e-01 5.38613119e-01
  8.80828923e-01 4.09926565e-01]
 [6.28996503e-01 1.11546357e-01 4.64316013e-01 5.31376150e-01
  1.73460642e-01 6.74615079e-01 2.63748783e-01 1.51193358e-01
  4.15431992e-01 2.27755618e-01]
 [6.46882815e-01 6.03758938e-02 7.34982830e-01 8.17947997e-01
  8.22833565e-01 1.96729714e-03 2.80577024e-01 5.07212950e-01
  2.24772015e-02 4.41511537e-01]
 [7.37390730e-01 1.23149993e-01 5.43426989e-01 5.42495700e-01
  7.12988220e-01 7.66995556e-01 2.79744976e-01 7.23938706e-02
  9.83066475e-01 7.67178766e-01]
 [8.27307024e-01 4.84074171e-01 2.50966868e-01 7.98866021e-01
  1.12042713e-01 9.32528751e-01 2.46974312e-04 4.18325124e-01
  5.65953351e-02 7.05365073e-01]
 [3.67199772e-01 6.84965597e-01 6.46860272e-01 5.73896573e

In [14]:
# Create a random vector of size 30 and find the mean value
arr = np.random.rand(30)
print(arr)
print("Mean: {}".format(np.mean(arr)))

[0.4632463  0.9039581  0.24948094 0.93019531 0.44528591 0.72800233
 0.21978343 0.64481306 0.59077537 0.45597021 0.6481628  0.43503212
 0.71415372 0.94766372 0.44309249 0.16641777 0.61428297 0.63567363
 0.61591412 0.81457647 0.91194217 0.55895547 0.03798414 0.10892575
 0.54249768 0.33886244 0.52128347 0.16564556 0.90086936 0.52464346]
Mean: 0.5426030089962283


In [15]:
# Create a 2d array with 1 on the border and 0 inside
n = 10
arr1 = np.ones(n)
arr2 = np.ones(n)
arr3 = np.ones(n)
arr2[1:-1] = 0
arr = np.array([arr1, arr2, arr3])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# How to add a border (filled with 0s) around an existing array?
existing_arr = np.arange(1,10).reshape(3,3)
np.pad(existing_arr, 1, "constant")

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# What is the result of the following expression?
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
0.3 == 3 * 0.1 # False

False

In [18]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr = np.zeros((5,5))
arr[1, 0] = 1
arr[2, 1] = 2
arr[3, 2] = 3
arr[4, 3] = 4
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [19]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
arr = np.zeros((8,8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [20]:
# Consider a (6, 7, 8) shape array, whatis the index (x, y, z) of the 100th element?
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [21]:
# Create a checkerboard 8x8 matrix using the tile function
arr = np.array([[0, 1], [1, 0]])
np.tile(arr, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
# Normalize a 5x5 random matrix
arr = np.random.rand(5,5)
print("Original 5x5 random matrix: \n{}\n".format(arr))
mx = np.max(arr)
mn = np.min(arr)
for i in range(arr[0].size):
    for j in range(arr[i].size):
        arr[i, j] = (arr[i, j] - mn) / (mx - mn)
print("Normalized 5x5 matrix: \n{}".format(arr))

Original 5x5 random matrix: 
[[0.67086761 0.6235856  0.58578996 0.76191608 0.39957225]
 [0.37578885 0.243982   0.84889571 0.42755862 0.54049476]
 [0.14714344 0.09104642 0.36758767 0.09229972 0.57776878]
 [0.43856573 0.07630628 0.49018837 0.63764994 0.3126695 ]
 [0.1722284  0.0685243  0.41330638 0.15088808 0.29332417]]

Normalized 5x5 matrix: 
[[0.77186747 0.71127836 0.66284548 0.88854072 0.42421845]
 [0.39374142 0.22483871 1.         0.46008134 0.60480234]
 [0.1007458  0.02886077 0.38323209 0.03046681 0.6525668 ]
 [0.4741863  0.00997215 0.54033767 0.72930098 0.3128577 ]
 [0.1328907  0.         0.44181793 0.10554433 0.28806779]]


In [23]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
np.dtype([('r', np.uint), ('g', np.uint), ('b', np.uint), ('a', np.uint)])

dtype([('r', '<u8'), ('g', '<u8'), ('b', '<u8'), ('a', '<u8')])

In [24]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print("{}\n".format(a))
print("{}\n".format(b))
print("Matrix product of the above two matrices:")
print(np.dot(a, b)) # Or a @ b

[[0.1413088  0.72407494 0.34899091]
 [0.26552658 0.3857327  0.57422419]
 [0.10201944 0.71933293 0.86208026]
 [0.74313624 0.95052408 0.87442218]
 [0.98041344 0.24029683 0.61264952]]

[[0.51504949 0.57056238]
 [0.47435285 0.78915232]
 [0.78630177 0.31190281]]

Matrix product of the above two matrices:
[[0.6906602  0.76088215]
 [0.77124623 0.63500348]
 [1.07161791 0.89475696]
 [1.52119545 1.4468486 ]
 [1.10067433 0.94010494]]


In [25]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
arr = np.arange(30)
np.random.shuffle(arr)
for i in range(len(arr)):
    if 3 <= arr[i] <= 8:
        arr[i] = -arr[i]
arr

array([-4, 22, 25, 19, 17,  0, 29, 23, 13,  2, 21, 10, 26, 14, 15, -8, 11,
       18, -5,  9, 20,  1, 27, 16, 28, 12, -6, 24, -3, -7])

In [26]:
# What is the output of the following script?
print(sum(range(5),-1)) # 10
from numpy import *
print(sum(range(5),-1)) # 10

9
10


In [27]:
# Consider an integer vector Z, which of these expressions are legal?
# All of the below expressions are legal!
Z = 5
Z**Z # 3125
2 << Z >> 2 # 16
Z <- Z # False
1j*Z # 5j
Z/1/1 # 5.0
Z<Z>Z # False

False

In [28]:
# What is the result of the following expression?
np.array(0) / np.array(0) # nan (RuntimeWarning: invalid value encountered in true_divide)
np.array(0) // np.array(0) # 0 (RuntimeWarning: divide by zero encountered in floor_divide)
np.array([np.nan]).astype(int).astype(float) # array([-9.22337204e+18])

/home/matthewmuccio/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/home/matthewmuccio/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [29]:
# How to round away from zero a float array?
arr = np.random.uniform(-5, 5, 10)
arr2 = np.round(arr + np.copysign(0.5, arr))
print(arr)
print(arr2)

[-3.60631636 -4.390308   -4.06620962 -4.18383337 -0.55177938  2.10684353
  1.89797462 -2.29018648  2.79734706  4.07314062]
[-4. -5. -5. -5. -1.  3.  2. -3.  3.  5.]


In [30]:
# How to find common values between two arrays?
arr = np.random.randint(-5, 5, 10)
arr2 = np.random.randint(-5, 5, 10)
arr3 = np.intersect1d(arr, arr2)
print(arr)
print(arr2)
print(arr3)

[-4  1  0  3  3  2 -2  4  2 -3]
[-2 -1  2 -4  1  2 -2  4  4 -3]
[-4 -3 -2  1  2  4]


In [31]:
# How to ignore all numpy warnings (not recommended)?
# Default: np.seterr(all="warn")
np.seterr(all="ignore")

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [32]:
# Is the following expression true?
# False
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [33]:
# How to get the dates of yesterday, today, and tomorrow?
today = np.datetime64("today")
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)
print("Today: {}".format(today))
print("Yesterday: {}".format(yesterday))
print("Tomorrow: {}".format(tomorrow))

Today: 2018-06-06
Yesterday: 2018-06-05
Tomorrow: 2018-06-07


In [34]:
# How to get all the dates corresponding to the month of July 2016?
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [35]:
# How to compute ((A+B)\*(-A/2)) in place (without copy)?
A = np.random.uniform(-5, 5, 5)
B = np.random.uniform(-5, 5, 5)
print(A)
print(B)
np.add(A, B, out=B)
np.negative(A, out=A)
np.multiply(A, 0.5, out=A) # np.divide(A, 2.0, out=A) causes a TypeError
np.multiply(A, B, out=A)
print(A)

[ 1.26527934 -3.0207656  -0.34901437  4.60060834  1.10915527]
[ 3.9591384  -3.86096017 -4.73856825  3.47961259 -3.39427386]
[ -3.30517393 -10.39404026  -0.88781973 -18.58696591   1.26727566]


In [36]:
# Extract the integer part of a random array using 5 different methods
arr = np.random.uniform(-15, 15, 10)
print(arr)
print(arr - arr % 1) # Only handles positives correctly, negatives round away
print(np.floor(arr))
print(np.ceil(arr) - 1)
print(arr.astype(int).astype(float)) # Handles positives and negatives correctly
print(np.trunc(arr))

[  7.95076187   4.81153149  12.35889098  12.69884701  14.90614176
  14.8537404   -7.81799129 -10.5634434   -4.42053537   0.52621947]
[  7.   4.  12.  12.  14.  14.  -8. -11.  -5.   0.]
[  7.   4.  12.  12.  14.  14.  -8. -11.  -5.   0.]
[  7.   4.  12.  12.  14.  14.  -8. -11.  -5.   0.]
[  7.   4.  12.  12.  14.  14.  -7. -10.  -4.   0.]
[  7.   4.  12.  12.  14.  14.  -7. -10.  -4.   0.]


In [37]:
# Create a 5x5 matrix with row values ranging from 0 to 4
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [38]:
# Consider a generator function that generates 10 integers and use it to build an array
n = 10
iterable = (n * np.random.rand() for x in range(n))
np.fromiter(iterable, float)

array([1.21331609, 1.58968035, 7.78210442, 8.20749175, 0.50168168,
       9.12135901, 3.92589997, 6.28606657, 6.20382117, 6.72206797])

In [39]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
arr = np.random.uniform(0, 1, 10) # Random values in (0, 1)
arr = np.linspace(0, 1, 11, endpoint=False)[1:] # Equally distributed values in (0, 1)
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [40]:
# Create a random vector of size 10 and sort it
arr = np.random.randint(-15, 15, 10)
np.sort(arr)

array([-13, -13, -10,  -7,  -4,  -2,   2,   3,   5,  14])

In [41]:
# How to sum a small array faster than np.sum?
arr = np.random.randint(-10, 10, 5)
arr_sum = np.add.reduce(arr)
print(arr)
print(arr_sum)

[ 8  3  2 -2  8]
19


In [42]:
# Consider two random arrays A and B, check if they are equal
A = np.random.randint(0, 2, 4)
B = np.random.randint(0, 2, 4)
result1 = np.allclose(A, B) # Assumes identical shape of arrays, and a tolerance for comparison of values
result2 = np.array_equal(A, B) # Checks for both identical array shape and values, no tolerance for comparison
print(A)
print(B)
print(result1)
print(result2)

[1 0 0 1]
[1 0 0 1]
True
True


In [43]:
# Make an array immutable (read-only)
arr = np.random.randint(-5, 5, 10)
arr.flags.writeable = False
arr
# Any future changes to arr will cause a ValueError

array([-4, -5,  2, -4, -1, -1, -5,  2,  1, -1])

In [44]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
arr = np.random.randint(0, 16, 20).reshape(10,2)
x = arr[:,0]
y = arr[:,1]
r = np.sqrt(x ** 2 + y ** 2) # r = sqrt(x^2 + y^2)
theta = np.arctan2(y, x) * 180 / np.pi # theta = [180 * arctan(y/x)] / pi
print("[X Y] (Cartesian coordinates)")
print(arr)
print("\n[r theta] (Polar coordinates)")
print(np.column_stack((r, theta)))

[X Y] (Cartesian coordinates)
[[ 7  2]
 [12  2]
 [ 2 15]
 [ 2 14]
 [ 3  5]
 [ 6 10]
 [ 6 14]
 [ 0  6]
 [ 6  1]
 [14 11]]

[r theta] (Polar coordinates)
[[ 7.28010989 15.9453959 ]
 [12.16552506  9.46232221]
 [15.13274595 82.40535663]
 [14.14213562 81.86989765]
 [ 5.83095189 59.03624347]
 [11.66190379 59.03624347]
 [15.23154621 66.80140949]
 [ 6.         90.        ]
 [ 6.08276253  9.46232221]
 [17.80449381 38.15722659]]


In [45]:
# Create random vector of size 10 and replace the maximum value by 0
arr = np.random.uniform(-10, 10, 10)
print(arr)
print("Max: {} at index {}".format(max(arr), np.argmax(arr)))
arr[np.argmax(arr)] = 0
print(arr)

[ 1.85345748  0.25723567  1.0802471  -1.93095049  7.41070903 -9.21347935
 -5.40364254  5.09201567 -0.49198117  8.37333566]
Max: 8.37333566135985 at index 9
[ 1.85345748  0.25723567  1.0802471  -1.93095049  7.41070903 -9.21347935
 -5.40364254  5.09201567 -0.49198117  0.        ]


In [46]:
# Create a structured array with x and y coordinates covering the [0,1] x [1,0] area
arr = np.zeros((5,5), [("x", float), ("y", float)])
arr["x"], arr["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))
X = np.random.uniform(-5, 5, 5)
Y = np.random.uniform(-5, 5, 5)
C = 1.0 / np.subtract.outer(X, Y)
C

array([[ 2.37698091e+00,  5.44483469e-01,  2.18841043e+00,
         1.71135550e-01,  4.88858349e-01],
       [-4.86807367e-01, -1.56666312e+00, -4.95552493e-01,
         2.96875191e-01, -2.32926467e+00],
       [-3.12723517e-01, -5.61226590e-01, -3.16309364e-01,
         4.49457051e-01, -6.35795717e-01],
       [-6.17027697e-01, -4.88349255e+00, -6.31145044e-01,
         2.63023149e-01,  2.37653951e+02],
       [-1.87070233e-01, -2.54473350e-01, -1.88347506e-01,
         1.29813451e+01, -2.68766246e-01]])

In [48]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.uint8, np.int8, np.uint16, np.int16, np.uint32, np.int32, np.uint64, np.int64]:
    print(dtype)
    print("Min: {}".format(np.iinfo(dtype).min))
    print("Max: {}".format(np.iinfo(dtype).max))
    print()
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(dtype)
    print("Min: {}".format(np.finfo(dtype).min))
    print("Max: {}".format(np.finfo(dtype).max))
    print("Eps: {}".format(np.finfo(dtype).eps))
    print()

<class 'numpy.uint8'>
Min: 0
Max: 255

<class 'numpy.int8'>
Min: -128
Max: 127

<class 'numpy.uint16'>
Min: 0
Max: 65535

<class 'numpy.int16'>
Min: -32768
Max: 32767

<class 'numpy.uint32'>
Min: 0
Max: 4294967295

<class 'numpy.int32'>
Min: -2147483648
Max: 2147483647

<class 'numpy.uint64'>
Min: 0
Max: 18446744073709551615

<class 'numpy.int64'>
Min: -9223372036854775808
Max: 9223372036854775807

<class 'numpy.float16'>
Min: -65504.0
Max: 65504.0
Eps: 0.0009765625

<class 'numpy.float32'>
Min: -3.4028234663852886e+38
Max: 3.4028234663852886e+38
Eps: 1.1920928955078125e-07

<class 'numpy.float64'>
Min: -1.7976931348623157e+308
Max: 1.7976931348623157e+308
Eps: 2.220446049250313e-16

<class 'numpy.float128'>
Min: -inf
Max: inf
Eps: 1.0842021724855044e-19



In [49]:
# How to print all the values of an array?
# Sets the total number of array elements which trigger summarization rather than a full representation to NaN.
np.set_printoptions(threshold=np.nan)
arr = np.arange(50)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [50]:
# How to find the closest value (to a given scalar) in a vector?
arr = np.arange(100) # Array with elements [0, 100)
scalar = np.random.uniform(0, 100) # A random scalar from [0, 100)
print(arr)
print(scalar)
print(arr[(np.abs(arr - scalar)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
4.05961786379102
4


In [51]:
# Create a structured array representing a position (x,y) and a color (r,g,b)
dtype = [
            ("position", [("x", float, 1),
                          ("y", float, 1)]),
            ("color", [("r", float, 1),
                       ("g", float, 1),
                       ("b", float, 1)])
        ]
np.zeros(1, dtype)

array([((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [52]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
arr = np.random.randint(-5, 5, (100,2))
x,y = np.atleast_2d(arr[:,0], arr[:,1])
distance = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2) # T = transpose()
print(arr)
print(distance)

[[-4  1]
 [ 1 -5]
 [-1 -3]
 [-4 -5]
 [ 2  1]
 [ 1  2]
 [-3  4]
 [ 1  4]
 [ 4  3]
 [-2  4]
 [-3 -2]
 [ 0 -3]
 [-3 -1]
 [-4 -1]
 [-1 -1]
 [-2  4]
 [-3  0]
 [ 4  2]
 [ 4  1]
 [ 2  3]
 [-1 -2]
 [-3  1]
 [-5  4]
 [-3  3]
 [-4 -1]
 [ 0 -4]
 [ 3  0]
 [ 1 -2]
 [-5 -2]
 [ 3 -3]
 [ 4  0]
 [-1  3]
 [ 2 -3]
 [ 4  3]
 [-5  4]
 [ 3 -4]
 [ 3 -4]
 [-5 -2]
 [-1 -3]
 [ 4  1]
 [-1 -5]
 [ 4 -1]
 [ 3  4]
 [-2  0]
 [-4  1]
 [-5 -5]
 [ 0  1]
 [ 4 -5]
 [-2  1]
 [ 4  4]
 [-1  0]
 [ 1 -2]
 [ 0  4]
 [ 2  2]
 [-2  1]
 [ 4  4]
 [-4 -2]
 [-2  3]
 [-1  3]
 [ 3 -3]
 [-2  1]
 [ 3  2]
 [ 0 -3]
 [ 0  0]
 [-2  0]
 [-5  0]
 [-3  3]
 [ 2  2]
 [ 0 -5]
 [-3  4]
 [-2 -5]
 [-5 -5]
 [ 0 -1]
 [-1  4]
 [-3 -4]
 [ 0  1]
 [ 3 -3]
 [ 3 -2]
 [ 2 -2]
 [ 0  4]
 [-1  1]
 [ 1  2]
 [-3  1]
 [ 1 -1]
 [-4 -3]
 [-4 -1]
 [-4 -1]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [-3 -2]
 [-3 -4]
 [ 1 -3]
 [-1  3]
 [ 3  1]
 [ 2 -5]
 [-4  3]
 [-3 -4]
 [-1 -5]
 [ 0 -3]]
[[ 0.          7.81024968  5.          6.          6.          5.09901951
   3.16227766  5.83095189

In [53]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?
arr = np.random.uniform(-10, 10, 10)
print(arr)
print(arr.astype(int, copy=False))

[ 3.64593476 -8.99495527 -9.05636576 -0.84456056 -6.42877159  9.61160755
  2.80957815 -0.83476821  5.17627633 -7.92100045]
[ 3 -8 -9  0 -6  9  2  0  5 -7]


In [54]:
# How to read the following file?
# Creating a "file" using StringIO module that contains the text
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n6,  ,  , 7, 8\n ,  , 9,10,11\n""")
print(s.getvalue())
print(np.genfromtxt(s, delimiter=",", dtype=np.int))

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [55]:
# What is the equivalent of enumerate for numpy arrays?
arr = np.random.randint(-10, 10, 9).reshape(3,3)
print(arr)
print("\nUsing np.ndenumerate:")
for i,v in np.ndenumerate(arr):
    print(i, v)
print("\nUsing np.ndindex:")
for i in np.ndindex(arr.shape):
    print(i, arr[i])

[[ 3 -6 -9]
 [ 1 -6 -4]
 [-6 -6 -2]]

Using np.ndenumerate:
(0, 0) 3
(0, 1) -6
(0, 2) -9
(1, 0) 1
(1, 1) -6
(1, 2) -4
(2, 0) -6
(2, 1) -6
(2, 2) -2

Using np.ndindex:
(0, 0) 3
(0, 1) -6
(0, 2) -9
(1, 0) 1
(1, 1) -6
(1, 2) -4
(2, 0) -6
(2, 1) -6
(2, 2) -2


In [56]:
# Generate a generic 2D Gaussian-like array
x,y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
distance = np.sqrt(x ** 2 + y ** 2)
sigma = 1.0
mu = 0.0
gaussian = np.exp(-((distance - mu) ** 2 / (2.0 * sigma ** 2)))
print(gaussian)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
# How to randomly place p elements in a 2D array?
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n ** 2), p, replace=False), 1)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
# Subtract the mean of each row of a matrix
arr = np.random.randint(-10, 10, (5,10))
new_arr = arr - arr.mean(axis=1, keepdims=True)
print("Initial random array: \n{}".format(arr))
print("\nMean of each row of initial array:")
for row in arr:
    print(row.mean())
print("\nNew array with mean of each row subtracted from each element: \n{}".format(new_arr))

Initial random array: 
[[  2  -2   9   1  -8  -5   9  -5  -9   6]
 [  9  -4  -6  -7  -6   9  -9   1  -4   9]
 [  7  -5   0   5   3  -9  -7   8  -3  -8]
 [  1  -6  -8   4  -1   2  -7  -5 -10   6]
 [ -9   0   9   4   7  -4  -5  -1  -8   9]]

Mean of each row of initial array:
-0.2
-0.8
-0.9
-2.4
0.2

New array with mean of each row subtracted from each element: 
[[ 2.2 -1.8  9.2  1.2 -7.8 -4.8  9.2 -4.8 -8.8  6.2]
 [ 9.8 -3.2 -5.2 -6.2 -5.2  9.8 -8.2  1.8 -3.2  9.8]
 [ 7.9 -4.1  0.9  5.9  3.9 -8.1 -6.1  8.9 -2.1 -7.1]
 [ 3.4 -3.6 -5.6  6.4  1.4  4.4 -4.6 -2.6 -7.6  8.4]
 [-9.2 -0.2  8.8  3.8  6.8 -4.2 -5.2 -1.2 -8.2  8.8]]


In [59]:
# How to sort an array by the nth column?
arr = np.random.randint(-10, 10, (3,3))
print("Initial random array: \n{}\n".format(arr))
print("Sorted array by the nth column: \n{}".format(arr[arr[:,1].argsort()]))

Initial random array: 
[[-1  8  3]
 [ 6 -6 -8]
 [ 2 -6 -7]]

Sorted array by the nth column: 
[[ 6 -6 -8]
 [ 2 -6 -7]
 [-1  8  3]]


In [60]:
# How to tell if a given 2D array has null columns (columns with all 0s)?
arr = np.random.randint(0, 3, (3,10))
print(arr)
print((~arr.any(axis=0)).any())

[[0 0 2 1 2 0 2 1 0 2]
 [1 0 1 0 1 2 2 1 2 2]
 [2 0 2 1 1 1 1 1 0 1]]
True


In [61]:
# Find the nearest value from a given value in an array
arr = np.random.rand(10)
val = 0.5
nearest = arr.flat[np.abs(arr - val).argmin()]
print(arr)
print(nearest)

[0.21021694 0.42024499 0.82719674 0.23825146 0.00196196 0.16496222
 0.64024082 0.8266677  0.55140452 0.63772867]
0.5514045236381928


In [62]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
arr1 = np.arange(3).reshape(1,3)
arr2 = np.arange(3).reshape(3,1)
iterator = np.nditer([arr1, arr2, None])
for x,y,z in iterator:
    z[...] = x + y
print(arr1)
print(arr2)
print(iterator.operands[2])

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
